HOST_PORT: ":8083"
READ_ONLY: false

CASSANDRA_HOST: cassandra
CASSANDRA_PORT: 9042
CASSANDRA_USERNAME:
CASSANDRA_PASSWORD:

BASIC_HTTP_AUTH_USER: "admin"
BASIC_HTTP_AUTH_PASSWORD: "admin"

APP_PATH:
